version: '3'

services:
  web:
    build: 
      context: ./
      dockerfile: ./containers/node/Dockerfile
    ports:
    - "8888:8080"
  mq:
    build:
      context: ./
      dockerfile: ./containers/rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
